(async()=>{
const targets=await (await fetch('http://127.0.0.1:9222/json')).json();
const target=targets.find(item=>item.type==='page'&&item.url.includes('manus.computer'))||targets.find(item=>item.type==='page');
if(!target)throw new Error('No page target found');
const ws=new WebSocket(target.webSocketDebuggerUrl);let nextId=1;const pending=new Map();
ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id&&pending.has(m.id)){const resolve=pending.get(m.id);pending.delete(m.id);resolve(m);}});
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,m=>m.error?reject(new Error(JSON.stringify(m.error))):resolve(m.result));ws.send(JSON.stringify({id,method,params}));});
await new Promise(resolve=>ws.addEventListener('open',resolve,{once:true}));
const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result?.value;
const run=async width=>{await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<700,touch:width<700});return await evaluate(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));const root=document.documentElement;const out=id=>document.getElementById(id)?.textContent.trim()||'';const click=async sel=>{document.querySelector(sel)?.click();await wait(60)};const input=(sel,value)=>{const e=document.querySelector(sel);if(e){e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}));}};const choose=(sel,value)=>{const e=document.querySelector(sel);if(e){e.value=value;e.dispatchEvent(new Event('change',{bubbles:true}));}};const submit=async sel=>{document.querySelector(sel)?.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await wait(60)};await submit('#scope-map-form');const scope=out('scope-map-output');await click('.content-mode-button[data-content-mode="technical"]');const mode=out('content-mode-output');await click('.annotation-marker[data-annotation="recovery"]');const annotation=out('annotation-output');await click('.tradeoff-button[data-tradeoff="privacy"]');const tradeoff=out('tradeoff-output');await click('[data-portal-view="decisions"]');const portal=out('portal-output');input('#portfolio-search-input','Python');await submit('#portfolio-search-form');const search=out('portfolio-search-output');await click('.incident-button[data-incident="asset"]');const incident=out('incident-output');await click('#contact-card-export');const contact=out('contact-card-output');await click('#quality-dashboard-run');const quality=out('quality-dashboard-output');await click('.dependency-button[data-dependency="llm"]');const dependency=out('dependency-output');await click('.brand-kit-button[data-brand="recruiter"]');const brand=out('brand-kit-output');const section=document.querySelector('#client-ready-layer');const overflow=[...document.querySelectorAll('#client-ready-layer *')].map(e=>{const r=e.getBoundingClientRect();return {tag:e.tagName,id:e.id||'',left:Math.round(r.left),right:Math.round(r.right),width:Math.round(r.width)}}).filter(x=>x.left< -1||x.right>innerWidth+1||x.width>innerWidth+1);return {width:${width},scrollWidth:root.scrollWidth,overflow,scope,mode,annotation,tradeoff,portal,search,incident,contact,quality,dependency,brand,cardCount:section?.querySelectorAll('.client-card').length||0}})()`)};const results=[];for(const width of [390,360,1280])results.push(await run(width));await send('Emulation.clearDeviceMetricsOverride');console.log(JSON.stringify({target:target.url,results},null,2));ws.close();
})();
