(async()=>{
const targets=await (await fetch('http://127.0.0.1:9222/json')).json();
const target=targets.find(item=>item.type==='page'&&item.url.includes('manus.computer'))||targets.find(item=>item.type==='page');
if(!target)throw new Error('No page target found');
const ws=new WebSocket(target.webSocketDebuggerUrl);let nextId=1;const pending=new Map();
ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id&&pending.has(m.id)){const resolve=pending.get(m.id);pending.delete(m.id);resolve(m);}});
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,m=>m.error?reject(new Error(JSON.stringify(m.error))):resolve(m.result));ws.send(JSON.stringify({id,method,params}));});
await new Promise(resolve=>ws.addEventListener('open',resolve,{once:true}));
const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result?.value;
const run=async(width)=>{await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<700});return await evaluate(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));const root=document.documentElement;const section=document.querySelector('#keyboard-guide');const button=document.querySelector('#keyboard-guide-toggle');const panel=document.querySelector('#keyboard-guide-panel');const rect=n=>{if(!n)return null;const r=n.getBoundingClientRect();return {left:Math.round(r.left),right:Math.round(r.right),top:Math.round(r.top),bottom:Math.round(r.bottom),width:Math.round(r.width),height:Math.round(r.height)}};button.focus();const initial={width:innerWidth,hidden:panel.hidden,expanded:button.getAttribute('aria-expanded'),focus:document.activeElement?.id||'',buttonText:button.textContent.trim(),panelTabIndex:panel.getAttribute('tabindex'),section:rect(section),scrollWidth:root.scrollWidth};button.click();await wait(50);const opened={hidden:panel.hidden,expanded:button.getAttribute('aria-expanded'),focus:document.activeElement?.id||'',buttonText:button.textContent.trim(),panel:rect(panel)};document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(50);const escaped={hidden:panel.hidden,expanded:button.getAttribute('aria-expanded'),focus:document.activeElement?.id||'',buttonText:button.textContent.trim()};button.click();await wait(30);button.click();await wait(30);const clickedClosed={hidden:panel.hidden,expanded:button.getAttribute('aria-expanded'),focus:document.activeElement?.id||''};button.click();await wait(30);document.querySelector('#language-toggle')?.click();await wait(120);const localized={rootLanguage:root.dataset.language||'',buttonText:button.textContent.trim(),firstDescription:panel.querySelector('dd')?.textContent.trim()||''};if(!panel.hidden){button.click();await wait(30)}const overflow=[...section.querySelectorAll('*')].filter(n=>{const r=n.getBoundingClientRect();return r.left< -1||r.right>innerWidth+1;}).map(n=>n.id||n.className||n.tagName);return {initial,opened,escaped,clickedClosed,localized,overflow,finalScrollWidth:root.scrollWidth}})()`);};const mobile=await run(390);await send('Emulation.clearDeviceMetricsOverride');const desktop=await run(1280);await send('Emulation.clearDeviceMetricsOverride');console.log(JSON.stringify({target:target.url,mobile,desktop},null,2));ws.close();
})();
