const targets = await fetch('http://127.0.0.1:9222/json').then(r => r.json());
const target = targets.find(item => item.type === 'page' && item.url.includes('manus.computer')) || targets.find(item => item.type === 'page');
if (!target) throw new Error('No page target found');
const ws = new WebSocket(target.webSocketDebuggerUrl);
let nextId = 1;
const pending = new Map();
ws.addEventListener('message', event => { const message = JSON.parse(event.data); if (message.id && pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id); } });
const send = (method, params = {}) => new Promise((resolve, reject) => { const id = nextId++; pending.set(id, message => message.error ? reject(new Error(JSON.stringify(message.error))) : resolve(message.result)); ws.send(JSON.stringify({id, method, params})); });
await new Promise(resolve => ws.addEventListener('open', resolve, {once:true}));
await send('Emulation.setDeviceMetricsOverride', {width:390,height:844,deviceScaleFactor:1,mobile:true});
const expression = `(() => {
  const root=document.documentElement; root.dataset.theme='light'; root.dataset.language='bn';
  const vw=innerWidth; const menu=document.querySelector('#site-menu'); const menuToggle=document.querySelector('#menu-toggle'); const qr=document.querySelector('#toggle-contact-qr'); const qrPanel=document.querySelector('#contact-qr-panel');
  const box=sel=>{const e=document.querySelector(sel);if(!e)return null;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {rect:{left:Math.round(r.left),right:Math.round(r.right),top:Math.round(r.top),bottom:Math.round(r.bottom),width:Math.round(r.width),height:Math.round(r.height)},display:s.display,font:s.fontSize,line:s.lineHeight,grid:s.gridTemplateColumns,gridColumn:s.gridColumn,text:(e.textContent||'').trim().slice(0,100)}};
  const out=()=>({scrollWidth:document.documentElement.scrollWidth,headerOut:[...document.querySelectorAll('.site-nav__inner>*')].map(e=>{const r=e.getBoundingClientRect();return {cls:String(e.className||''),left:Math.round(r.left),right:Math.round(r.right),display:getComputedStyle(e).display}}).filter(x=>x.display!=='none'&&(x.left<0||x.right>vw)),contactOut:[...document.querySelectorAll('#contact *')].map(e=>{const r=e.getBoundingClientRect();return {id:e.id||'',left:Math.round(r.left),right:Math.round(r.right),width:Math.round(r.width)}}).filter(x=>x.left<0||x.right>vw||x.width>vw),form:box('#ai-grounded-form'),consent:box('#ai-grounded-form>.v25-consent'),span:box('#ai-grounded-form>.v25-consent span'),qr:{hidden:qrPanel?.hidden,aria:qr?.getAttribute('aria-expanded'),text:qr?.textContent},qrPanel:box('#contact-qr-panel')});
  const before=out(); menuToggle?.click(); const open={menu:menu?.classList.contains('is-open'),lock:document.body.classList.contains('menu-open'),aria:menuToggle?.getAttribute('aria-expanded'),mobileTools:document.querySelectorAll('#site-nav-mobile-tools .utility-toggle').length}; menuToggle?.click(); qr?.click(); const qrOpen=out(); qr?.click(); const closed={menu:menu?.classList.contains('is-open'),lock:document.body.classList.contains('menu-open'),aria:menuToggle?.getAttribute('aria-expanded'),qrHidden:qrPanel?.hidden,qrAria:qr?.getAttribute('aria-expanded')}; return {before,open,qrOpen,closed};
})()`;
const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});
console.log(JSON.stringify({target:target.url,result:result.result?.value},null,2));
await send('Emulation.clearDeviceMetricsOverride'); ws.close();
