(async()=>{
const targets=await (await fetch('http://127.0.0.1:9222/json')).json();
const target=targets.find(item=>item.type==='page'&&item.url.includes('manus.computer'))||targets.find(item=>item.type==='page');
if(!target)throw new Error('No page target found');
const ws=new WebSocket(target.webSocketDebuggerUrl);let nextId=1;const pending=new Map();
ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id&&pending.has(m.id)){const resolve=pending.get(m.id);pending.delete(m.id);resolve(m);}});
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,m=>m.error?reject(new Error(JSON.stringify(m.error))):resolve(m.result));ws.send(JSON.stringify({id,method,params}));});
await new Promise(resolve=>ws.addEventListener('open',resolve,{once:true}));
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
const expression=`(async()=>{
 const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));const root=document.documentElement;
 const rect=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {left:Math.round(r.left),right:Math.round(r.right),top:Math.round(r.top),bottom:Math.round(r.bottom),width:Math.round(r.width),height:Math.round(r.height),font:s.fontSize,color:s.color,text:(e.textContent||'').trim().slice(0,180)}};
 const section=document.querySelector('#professional-delivery');const cards=[...document.querySelectorAll('#professional-delivery .delivery-card')];
 const initial={present:!!section,cards:cards.length,forms:document.querySelectorAll('#professional-delivery form').length,scrollWidth:root.scrollWidth,sectionHeight:section?Math.round(section.getBoundingClientRect().height):0};
 const preflight=document.querySelector('#contact-preflight-form');document.querySelector('#preflight-goal').value='Build a searchable document workflow';document.querySelector('#preflight-platform').value='telegram';document.querySelector('#preflight-deadline').value='month';preflight?.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await wait(30);const preflightResult=document.querySelector('#contact-preflight-output')?.textContent.trim()||'';
 const risk=document.querySelector('#risk-project');risk.value='deepseek';risk.dispatchEvent(new Event('change',{bubbles:true}));await wait(20);const riskResult=document.querySelector('#risk-matrix-output')?.textContent.trim()||'';
 document.querySelector('.threat-button[data-threat="provider"]')?.click();await wait(20);const threatResult=document.querySelector('#threat-model-output')?.textContent.trim()||'';
 document.querySelector('.workflow-button[data-workflow="after"]')?.click();await wait(20);const workflowResult=document.querySelector('#workflow-simulator-output')?.textContent.trim()||'';
 document.querySelector('.claim-buttons button[data-claim="llm"]')?.click();await wait(20);const claimResult=document.querySelector('#claim-proof-output')?.textContent.trim()||'';
 document.querySelector('#release-verification-check')?.click();await wait(20);const releaseResult=document.querySelector('#release-verification-output')?.textContent.trim()||'';
 document.querySelector('.route-buttons a[data-route="deepseek"]')?.click();await wait(20);document.querySelector('#share-route-copy')?.click();await wait(1000);const routeResult=document.querySelector('#share-route-output')?.textContent.trim()||'';
 document.querySelector('#handoff-copy')?.click();await wait(1000);const handoffResult=document.querySelector('#handoff-output')?.textContent.trim()||'';
 document.querySelector('#design-tone').value='blue';document.querySelector('#design-tone').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('#design-scale').value='large';document.querySelector('#design-scale').dispatchEvent(new Event('change',{bubbles:true}));await wait(20);const design={tone:document.querySelector('#design-preview')?.dataset.tone||'',scale:document.querySelector('#design-preview')?.dataset.scale||'',preview:document.querySelector('#design-preview')?rect(document.querySelector('#design-preview')):null};
 const overflow=cards.flatMap(card=>[...card.querySelectorAll('*')].filter(child=>{const r=child.getBoundingClientRect();return r.left< -1||r.right>root.clientWidth+1;}).map(child=>child.id||child.className||child.tagName));
 const lang=document.querySelector('#language-toggle');lang?.click();await wait(80);const language={value:root.dataset.language||'',title:document.querySelector('#professional-delivery-title')?.textContent.trim()||'',risk:document.querySelector('#risk-matrix-output')?.textContent.trim()||''};
 const theme=document.querySelector('#theme-toggle');if(root.dataset.theme!=='light')theme?.dispatchEvent(new MouseEvent('click',{bubbles:true}));await wait(50);const light={theme:root.dataset.theme||'',title:document.querySelector('#professional-delivery-title')?rect(document.querySelector('#professional-delivery-title')):null,card:document.querySelector('.delivery-card h3')?rect(document.querySelector('.delivery-card h3')):null};
 return {initial,preflightResult,riskResult,threatResult,workflowResult,claimResult,releaseResult,routeResult,handoffResult,design,overflow,language,light,finalScrollWidth:root.scrollWidth};
})()`;
const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});console.log(JSON.stringify({target:target.url,result:result.result?.value||result.exceptionDetails},null,2));await send('Emulation.clearDeviceMetricsOverride');ws.close();
})();
