(async()=>{
const targets=await (await fetch('http://127.0.0.1:9222/json')).json();
const target=targets.find(item=>item.type==='page'&&item.url.includes('manus.computer'))||targets.find(item=>item.type==='page');
if(!target)throw new Error('No page target found');
const ws=new WebSocket(target.webSocketDebuggerUrl);let nextId=1;const pending=new Map();
ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id&&pending.has(m.id)){const resolve=pending.get(m.id);pending.delete(m.id);resolve(m);}});
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,m=>m.error?reject(new Error(JSON.stringify(m.error))):resolve(m.result));ws.send(JSON.stringify({id,method,params}));});
await new Promise(resolve=>ws.addEventListener('open',resolve,{once:true}));
const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result?.value;
const run=async(width)=>{await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<700,touch:width<700});return await evaluate(`(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));const root=document.documentElement;const rect=n=>{if(!n)return null;const r=n.getBoundingClientRect(),s=getComputedStyle(n);return {left:Math.round(r.left),right:Math.round(r.right),top:Math.round(r.top),bottom:Math.round(r.bottom),width:Math.round(r.width),height:Math.round(r.height),opacity:s.opacity,display:s.display,pointerEvents:s.pointerEvents}};const buttons=['archive','deepseek','portfolio'].map(key=>{const e=document.querySelector('.project-card [data-preview="'+key+'"]');return {key,found:!!e,box:rect(e),text:e?.textContent.trim()||''}});const dialog=document.querySelector('#project-dialog'),image=document.querySelector('#dialog-image');const previews=[];for(const key of ['archive','deepseek','portfolio']){const button=document.querySelector('.project-card [data-preview="'+key+'"]');button?.click();await wait(70);previews.push({key,open:!!dialog?.open,title:document.querySelector('#dialog-title')?.textContent.trim()||'',src:image?.getAttribute('src')||'',imageLoaded:!!image?.complete&&image.naturalWidth>0,naturalWidth:image?.naturalWidth||0});document.querySelector('#dialog-close')?.click();await wait(25)}const deep=document.querySelector('#deep-preview');deep?.click();await wait(70);const deepPreview={open:!!dialog?.open,title:document.querySelector('#dialog-title')?.textContent.trim()||'',imageLoaded:!!image?.complete&&image.naturalWidth>0};document.querySelector('#dialog-close')?.click();const overflow=[...document.querySelectorAll('#projects *,#case-studies *,#project-dialog *')].map(e=>{const r=e.getBoundingClientRect();return {id:e.id||'',cls:String(e.className||'').slice(0,60),left:Math.round(r.left),right:Math.round(r.right),width:Math.round(r.width)}}).filter(x=>x.left< -1||x.right>innerWidth+1||x.width>innerWidth+1);return {width:${width},scrollWidth:root.scrollWidth,buttons,previews,deepPreview,overflow}})()`)};const results=[];for(const width of [390,360,1280])results.push(await run(width));await send('Emulation.clearDeviceMetricsOverride');console.log(JSON.stringify({target:target.url,results},null,2));ws.close();
})();
